<?php

namespace AppBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * NoticiaRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class NoticiaRepository extends EntityRepository
{

    public function getUltimasNoticias()
    {
        $qb = $this->createQueryBuilder('n');

        $qb->orderBy('n.creado', ' DESC')
            ->setMaxResults(10);

        return $qb->getQuery()->getResult();
    }

    private $itemsPorPagina = 10;

    public function getNoticiasByPage($page)
    {
        $hoy = new \DateTime();
        $qb = $this->createQueryBuilder('a')
            ->andWhere('a.activo = true ')
            ->andWhere(':hoy BETWEEN a.visibleDesde AND a.visibleHasta')
            ->setParameter('hoy', $hoy)
//            ->setMaxResults($this->itemsPorPagina)
            ->orderBy('a.orden', 'ASC')
            ->orderBy('a.creado', 'ASC');


        return $qb->getQuery()->getResult();
    }
}
