agenda_index:
    path:     /
    defaults: { _controller: "AppBundle:Agenda:index" }
    methods:  GET

agenda_show:
    path:     /{id}/show
    defaults: { _controller: "AppBundle:Agenda:show" }
    methods:  GET

agenda_new:
    path:     /new
    defaults: { _controller: "AppBundle:Agenda:new" }
    methods:  [GET, POST]

agenda_edit:
    path:     /{id}/edit
    defaults: { _controller: "AppBundle:Agenda:edit" }
    methods:  [GET, POST]

agenda_delete:
    path:     /{id}/delete
    defaults: { _controller: "AppBundle:Agenda:delete" }
    methods:  DELETE
