noticias_index:
    path:     /
    defaults: { _controller: "AppBundle:Noticia:index" }
    methods:  GET

noticias_show:
    path:     /{id}/show
    defaults: { _controller: "AppBundle:Noticia:show" }
    methods:  GET

noticias_new:
    path:     /new
    defaults: { _controller: "AppBundle:Noticia:new" }
    methods:  [GET, POST]

noticias_edit:
    path:     /{id}/edit
    defaults: { _controller: "AppBundle:Noticia:edit" }
    methods:  [GET, POST]

noticias_delete:
    path:     /{id}/delete
    defaults: { _controller: "AppBundle:Noticia:delete" }
    methods:  DELETE
