#easy admin
easy_admin:
    site_name: 'TURISMO'
    design:
        brand_color: '#e66500'
        menu:
            - 'Atraccion'
            - 'Noticia'
            - 'Agenda'
            - 'Contacto'
            - label: 'Categorias'
              children:
                  - { entity: 'CategoriaNoticia', label: 'Categoria Noticia' }
                  - { entity: 'CategoriaAgenda', label: 'Categoria Agenda' }
                  - { entity: 'CategoriaAtraccion', label: 'Categoria Atraccion' }
            - label: 'Ubicacion'
              children:
                  - 'Pais'
                  - 'Provincia'
                  - 'Departamento'
                  - 'Localidad'
            - 'Usuario'
            - { label: 'Cerrar Sesion', route: 'fos_user_security_logout', icon: 'sign-out' }
        assets:
            css:
                - '/bundles/app/css/style.css'
                - '/bundles/app/plugins/bootstrap-datepicker-1.5.1/css/bootstrap-datepicker3.min.css'
                - '//maxcdn.bootstrapcdn.com/bootstrap/3.3.1/css/bootstrap.min.css'
                - 'http://maxcdn.bootstrapcdn.com/font-awesome/4.3.0/fonts/fontawesome-webfont.eot?v=4.3.0'
                - '//maxcdn.bootstrapcdn.com/font-awesome/4.3.0/css/font-awesome.min.css'
                - '//cdn.rawgit.com/Eonasdan/bootstrap-datetimepicker/e8bddc60e73c1ec2475f827be36e1957af72e2ea/build/css/bootstrap-datetimepicker.css'
            js:
                - '/bundles/app/js/app.js'
                - '/bundles/app/plugins/bootstrap-datepicker-1.5.1/js/bootstrap-datepicker.min.js'
                - '/bundles/app/plugins/bootstrap-datepicker-1.5.1/locales/bootstrap-datepicker.es.min.js'
                - '//cdnjs.cloudflare.com/ajax/libs/moment.js/2.9.0/moment-with-locales.js'
                - '//cdn.rawgit.com/Eonasdan/bootstrap-datetimepicker/e8bddc60e73c1ec2475f827be36e1957af72e2ea/src/js/bootstrap-datetimepicker.js'

    entities:
        Atraccion:
            class: AppBundle\Entity\Atraccion
            list:
                actions:
                - { name: '-edit'}
                - { name: 'atraccion_edit', type: 'route', icon: 'pencil', label: '' }
                - { name: 'delete', icon: 'trash', label: '' }
        Noticia:
            class: AppBundle\Entity\Noticia
            list:
                actions:
                    - { name: '-edit'}
                    - { name: 'noticias_edit', type: 'route', icon: 'pencil', label: '' }
                    - { name: 'delete', icon: 'trash', label: '' }

        Agenda:
            class: AppBundle\Entity\Agenda
            list:
                actions:
                    - { name: '-edit'}
                    - { name: 'agenda_edit', type: 'route', icon: 'pencil', label: '' }
                    - { name: 'delete', icon: 'trash', label: '' }
