#easy admin
easy_admin:
    entities:
        CategoriaNoticia:
            class: AppBundle\Entity\CategoriaNoticia
            form:
                fields:
                    - { property: 'nombre', type: 'text' }
                    - { property: 'descripcion', type: 'text' }
                    - { property: 'icono', type: 'text' }